# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: CmdLine@2
      inputs:
        script: |
          docker login --username $(DOCKER_HUB_USERNAME) --password $(DOCKER_HUB_ACCESS_TOKEN)

          (cd swift-docker/5.4 && docker build --rm --tag kishikawakatsumi/swift:5.4 . && docker push kishikawakatsumi/swift:5.4)
          docker system prune -a -f

          (cd swift-docker/5.4.1 && docker build --rm --tag kishikawakatsumi/swift:5.4.1 . && docker push kishikawakatsumi/swift:5.4.1)
          docker system prune -a -f

          (cd swift-docker/5.3 && docker build --rm --tag kishikawakatsumi/swift:5.3 . && docker push kishikawakatsumi/swift:5.3)
          docker system prune -a -f

          (cd swift-docker/5.3.1 && docker build --rm --tag kishikawakatsumi/swift:5.3.1 . && docker push kishikawakatsumi/swift:5.3.1)
          docker system prune -a -f

          (cd swift-docker/5.3.2 && docker build --rm --tag kishikawakatsumi/swift:5.3.2 . && docker push kishikawakatsumi/swift:5.3.2)
          docker system prune -a -f

          (cd swift-docker/5.3.3 && docker build --rm --tag kishikawakatsumi/swift:5.3.3 . && docker push kishikawakatsumi/swift:5.3.3)
          docker system prune -a -f
