version: "3.7"

services:
  app:
    build:
      context: .
    container_name: swift-playground
    depends_on:
      - nginx-proxy
    env_file:
      - .env
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-info}
    ports:
      - 8080:8080
    user: "0"
    command:
      [
        "serve",
        "--env",
        "production",
        "--hostname",
        "0.0.0.0",
        "--port",
        "8080",
      ]
