version: "3.7"

services:
  app:
    build:
      context: .
    container_name: swift-playground
    depends_on:
      - nginx-proxy
      - carbonara
    env_file:
      - .env
    environment:
      HOST_PWD: $PWD/
      LOG_LEVEL: ${LOG_LEVEL:-info}
      VIRTUAL_HOST: localhost,127.0.0.1
      VIRTUAL_PORT: 8080
    ports:
      - 8080:8080
    user: "0"
    command:
      [
        "serve",
        "--env",
        "production",
        "--hostname",
        "0.0.0.0",
        "--port",
        "8080",
      ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $PWD/Resources/Temp:/app/Resources/Temp
    links:
      - carbonara
    restart: always

  carbonara:
    image: petersolopov/carbonara
    container_name: carbonara
    ports:
      - 3000:3000
    cap_add:
      - SYS_ADMIN
    restart: always

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    environment:
      DEFAULT_EMAIL: kishikawakatsumi@mac.com
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx-proxy/conf.d:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always

  swift-5.4.2:
    image: kishikawakatsumi/swift:5.4.2
    container_name: swift-5.4.2

volumes:
  vhost:
  html:
  dhparam:
  certs:
