apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: kishikawakatsumi@mac.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - dns01:
          cloudflare:
            email: kishikawakatsumi@mac.com
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: zerossl
spec:
  acme:
    server: https://acme.zerossl.com/v2/DV90
    externalAccountBinding:
      keyID: UPtogZUupKNYZSf7fUbWHg
      keySecretRef:
        name: zerossl-eab-key
        key: eab-key
    privateKeySecretRef:
      name: zerossl
    solvers:
      - dns01:
          cloudflare:
            email: kishikawakatsumi@mac.com
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
