apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: limitrange
spec:
  limits:
    - type: "Container"
      max:
        memory: "512Mi"
      min:
        memory: "64Mi"
      default:
        memory: "512Mi"
      defaultRequest:
        memory: "128Mi"
