apiVersion: v1
kind: Service
metadata:
  name: web-frontend
  annotations:
    cloud.google.com/backend-config: '{"ports": {"80": "backendconfig"}}'
spec:
  selector:
    app.kubernetes.io/name: web-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort

---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: backendconfig
spec:
  timeoutSec: 660
  connectionDraining:
    drainingTimeoutSec: 720

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-frontend
  labels:
    app.kubernetes.io/name: web-frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: web-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: web-frontend
      annotations:
        commit_sha: "be823b67938beb39db90cd456943427a02126766"
    spec:
      containers:
        - image: swiftfiddle/web-frontend:latest
          name: web-frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
          env:
            - name: FIREBASE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: FIREBASE_API_KEY
            - name: FIREBASE_REFRESH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: FIREBASE_REFRESH_TOKEN
            - name: GCP_PROJECT
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: GCP_PROJECT
