apiVersion: v1
kind: Service
metadata:
  name: web-frontend
spec:
  selector:
    app.kubernetes.io/name: web-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-frontend
  labels:
    app.kubernetes.io/name: web-frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: web-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: web-frontend
      annotations:
        commit_sha: 8ecc7cd34ca74fe203ad92b37f95026436e6ed2e
    spec:
      containers:
        - image: swiftfiddle/web-frontend:latest
          name: web-frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
          env:
            - name: FIREBASE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: FIREBASE_API_KEY
            - name: FIREBASE_REFRESH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: FIREBASE_REFRESH_TOKEN
            - name: GCP_PROJECT
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: GCP_PROJECT
