apiVersion: v1
kind: Service
metadata:
  name: web-frontend
spec:
  selector:
    app.kubernetes.io/name: web-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort

---
apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: limitrange
spec:
  limits:
    - type: "Container"
      max:
        cpu: 200m
        memory: 2Gi
      min:
        cpu: 0m
        memory: 32Mi
      default:
        cpu: 100m
        memory: 512Mi
      defaultRequest:
        cpu: 10m
        memory: 128Mi

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: web-frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-frontend
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: AverageValue
          averageValue: 250m
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: 128Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-frontend
  labels:
    app.kubernetes.io/name: web-frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: web-frontend
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  minReadySeconds: 60
  progressDeadlineSeconds: 600
  template:
    metadata:
      labels:
        app.kubernetes.io/name: web-frontend
      annotations:
        commit_sha: "%COMMIT_SHA%"
    spec:
      nodeSelector:
        name: defaultpool
      containers:
        - image: swiftfiddle.azurecr.io/swiftfiddle/web-frontend:latest
          name: web-frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 10
            failureThreshold: 1
          resources:
            limits:
              cpu: 40m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 32Mi
          env:
            - name: FIREBASE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: FIREBASE_API_KEY
            - name: FIREBASE_REFRESH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: FIREBASE_REFRESH_TOKEN
            - name: GCP_PROJECT
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: GCP_PROJECT
      terminationGracePeriodSeconds: 60
