apiVersion: v1
kind: Service
metadata:
  name: web-frontend
  annotations:
    cloud.google.com/backend-config: '{"ports": {"80": "backendconfig"}}'
spec:
  selector:
    app.kubernetes.io/name: web-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort

---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: frontendconfig
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT

---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: backendconfig
spec:
  timeoutSec: 660
  connectionDraining:
    drainingTimeoutSec: 720

---
apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: limitrange
spec:
  limits:
    - type: "Container"
      max:
        cpu: 500m
        memory: 1Gi
      min:
        cpu: 50m
        memory: 64Mi
      default:
        cpu: 250m
        memory: 512Mi
      defaultRequest:
        cpu: 100m
        memory: 128Mi

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: web-frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-frontend
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: AverageValue
          averageValue: 250m
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: 128Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-frontend
  labels:
    app.kubernetes.io/name: web-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: web-frontend
  minReadySeconds: 60
  progressDeadlineSeconds: 600
  template:
    metadata:
      labels:
        app.kubernetes.io/name: web-frontend
      annotations:
        commit_sha: "%COMMIT_SHA%"
    spec:
      containers:
        - image: us.gcr.io/swift-playground-fbe87/web-frontend:latest
          name: web-frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 10
            failureThreshold: 1
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 64Mi
          env:
            - name: FIREBASE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: FIREBASE_API_KEY
            - name: FIREBASE_REFRESH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: FIREBASE_REFRESH_TOKEN
            - name: GCP_PROJECT
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: GCP_PROJECT
      terminationGracePeriodSeconds: 60
