name: Build Docker Images
on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Images
        run: |
          (cd swift-docker/5.3 && docker build --rm --tag ${{ secrets.DOCKER_HUB_USERNAME }}/swift:5.3 .)
          (cd swift-docker/5.3.1 && docker build --rm --tag ${{ secrets.DOCKER_HUB_USERNAME }}/swift:5.3.1 .)
          (cd swift-docker/5.3.2 && docker build --rm --tag ${{ secrets.DOCKER_HUB_USERNAME }}/swift:5.3.2 .)
          (cd swift-docker/5.3.3 && docker build --rm --tag ${{ secrets.DOCKER_HUB_USERNAME }}/swift:5.3.3 .)
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Push to DockerHub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/swift:5.3,${{ secrets.DOCKER_HUB_USERNAME }}/swift:5.3.1,${{ secrets.DOCKER_HUB_USERNAME }}/swift:5.3.2,${{ secrets.DOCKER_HUB_USERNAME }}/swift:5.3.3
