name: Update Package.resolved
on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  run:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: SwiftyLab/setup-swift@latest
      - name: Update Package.swift.json
        run: |
          set -ex

          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"

          git pull --rebase origin master

          tempdir=$(mktemp -d)
          filename="Package.swift"
          curl -sfL -o "$tempdir/$filename" https://raw.github.com/swiftfiddle/swiftfiddle-lsp/main/Resources/ProjectTemplate/$filename
          swift package --package-path "$tempdir" dump-package > Resources/$filename.json

          git add Resources/$filename.json
          git diff-index --quiet HEAD || git commit -m "Update $filename.json"
          git push origin master
      - name: Build
        run: |
          set -ex

          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"

          git pull --rebase origin master

          swift package update
          swift build

          git add Package.resolved
          git diff-index --quiet HEAD || git commit -m "Update Package.resolved"
          git push origin master
